### ISSUE TITLE
Apple Mach-O linker error on trying to build, Xcode 6.2

### ISSUE THREAD

**Issue by gunshi** [aptogo/FaceTracker#3]
I'm trying to compile the project as it is, on Xcode 6.2, and the iPhone 6 simulator is selected for testing, yet it gives me this error.
i'm confused as to why it is even looking for symbols for x86_64, since i'm building for iOS devices.
Any help would be appreciated.Thanks!

ld: warning: ignoring file /Users/gunshigupta/Downloads/FaceTracker-master/OpenCV.framework/OpenCV, missing required architecture x86_64 in file /Users/gunshigupta/Downloads/FaceTracker-master/OpenCV.framework/OpenCV (3 slices)
Undefined symbols for architecture x86_64:
  "cv::_InputArray::_InputArray(cv::Mat const&)", referenced from:
      -[DemoVideoCaptureViewController processFrame:videoRect:videoOrientation:] in DemoVideoCaptureViewController.o
  "cv::_OutputArray::_OutputArray(cv::Mat&)", referenced from:
      -[DemoVideoCaptureViewController processFrame:videoRect:videoOrientation:] in DemoVideoCaptureViewController.o
  "cv::CascadeClassifier::load(std::string const&)", referenced from:
      -[DemoVideoCaptureViewController viewDidLoad] in DemoVideoCaptureViewController.o
  "cv::CascadeClassifier::CascadeClassifier()", referenced from:
      -[DemoVideoCaptureViewController .cxx_construct] in DemoVideoCaptureViewController.o
  "cv::CascadeClassifier::~CascadeClassifier()", referenced from:
      -[DemoVideoCaptureViewController .cxx_destruct] in DemoVideoCaptureViewController.o
  "cv::Mat::deallocate()", referenced from:
      cv::Mat::release() in VideoCaptureViewController.o
      cv::Mat::release() in UIImage+OpenCV.o
  "cv::Mat::create(int, int const*, int)", referenced from:
      cv::Mat::create(int, int, int) in UIImage+OpenCV.o
  "cv::flip(cv::_InputArray const&, cv::_OutputArray const&, int)", referenced from:
      -[DemoVideoCaptureViewController processFrame:videoRect:videoOrientation:] in DemoVideoCaptureViewController.o
  "cv::resize(cv::_InputArray const&, cv::_OutputArray const&, cv::Size_<int>, double, double, int)", referenced from:
      -[DemoVideoCaptureViewController processFrame:videoRect:videoOrientation:] in DemoVideoCaptureViewController.o
  "cv::fastFree(void*)", referenced from:
      cv::Mat::~Mat() in VideoCaptureViewController.o
      cv::Mat::~Mat() in UIImage+OpenCV.o
  "cv::transpose(cv::_InputArray const&, cv::_OutputArray const&)", referenced from:
      -[DemoVideoCaptureViewController processFrame:videoRect:videoOrientation:] in DemoVideoCaptureViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Nualiian** [comment]
@gunshi how did you solve it in the end, if I may ask?
